#!/usr/bin/env bash
# Generate an Ansible inventory from Terraform outputs.
#   usage: generate_inventory.sh <env> <inventory_file>
#   env:   VM_INFO     (terraform output -json vm_connection_info)  required
#          CREDENTIALS (terraform output -json vm_credentials)      required
#          PASSWORDS   (terraform output -json vm_passwords)        only with ANSIBLE_USE_PASSWORDS=true
# Hosts go into [<env>]. VMs with a non-empty "role" are also listed in [<env>_<role>] (hyphens -> underscores).
set -euo pipefail

ENV_NAME=$1
OUT=$2
USE_PW=${ANSIBLE_USE_PASSWORDS:-false}
PW=${PASSWORDS-}
[ -n "$PW" ] || PW='{}'

mkdir -p "$(dirname "$OUT")"
{
  echo "# Generated by task ansible:generate-inventory (env: $ENV_NAME)"
  echo "[$ENV_NAME]"
  jq -r --arg use "$USE_PW" --argjson cred "$CREDENTIALS" --argjson pw "$PW" '
    to_entries[] | .key as $k | .value as $v |
    "\($v.name) ansible_host=\($v.ip_address) ansible_user=\($cred[$k].username)"
    + (if $use == "true" then " ansible_password=\($pw[$k]) ansible_become_password=\($pw[$k])" else "" end)
  ' <<<"$VM_INFO"

  jq -r '[.[] | .role // "" | select(. != "")] | unique[]' <<<"$VM_INFO" | while read -r role; do
    echo
    echo "[${ENV_NAME}_$(printf '%s' "$role" | tr '-' '_')]"
    jq -r --arg r "$role" '.[] | select((.role // "") == $r) | .name' <<<"$VM_INFO"
  done
} > "$OUT"
chmod 0600 "$OUT"
echo "Inventory file generated: $OUT"
