version: '3'

tasks:
  push-secrets:
    desc: "Encodes JSON file and push it to GitHub Actions secrets"
    dir: "{{.USER_WORKING_DIR}}"
    silent: true
    vars:
      encoded: "{{cat .CLI_ARGS | b64enc}}"
      secret_name: "{{.CLI_ARGS | fromSlash | splitList \"/\" | last | replace \".tfvars.json\" \"\" | replace \" \" \"_\" | replace \"-\" \"_\" | replace \".\" \"_\" | upper}}"
    cmds:
      - echo {{ .encoded }}
      - echo {{ .secret_name }}

  push-tfvars:
    desc: "Encodes the content of all files ending with tfvars.json in the specified directory"
    dir: "{{.USER_WORKING_DIR}}"
    silent: true
    vars:
      files:
        sh: find {{.CLI_ARGS}} -name "*tfvars.json" -type f -print0
    cmds:
      - for: { var: files }
        task: push-secrets
        vars:
          CLI_ARGS: "{{.ITEM}}"
