vault_tailscale_oauth_client_secret: ENC[AES256_GCM,data:tnfIeqrvGvpksaL6k8Nc9V7G+42yOtTEekJlZsKZqOViq5wnojjumo8p3pz75T/tYMyHx+hd7meUKIqM1ces,iv:iRtzBYTH5BLHc8J0/ofwHfoC5+AvYbANZmRZZCZZhBs=,tag:bN4iWcxPe3Eu7cEKAA3lIQ==,type:str]
vault_zabbix_db_password: ENC[AES256_GCM,data:JHD+IBhaHRD7Wyec8EOhgUkckkRiWv3K5vK5tNPF7Ew=,iv:T0IBymOwgdOqgb6MGSUsfFZMbs9B7VwaXr8bgnEhBDo=,tag:rCXoynT3epQ3g/W9K0BmHQ==,type:str]
vault_zabbix_admin_password: ENC[AES256_GCM,data:LPCwkrpgvhku5gs0KmFu,iv:m7PwBQbcA0k4mGwrqnls/b7Xo1dZ3kb2n9wWOx4/INs=,tag:wamyrqLdjJ9MY1QgS9J0Lw==,type:str]
vault_zabbix_snmp_community: ENC[AES256_GCM,data:88q+UE8dI46frqiowME1eExj+Hg=,iv:EhGu+XK6OV0KStH/rbSnxNZlzPNEb23s8KTw6UHINdo=,tag:6XsbjoAdgGm6ZiSl93mJWw==,type:str]
vault_slack_bot_token: ENC[AES256_GCM,data:uIMVRnnTBeq3Ss609hp7dumozTquPU7qf8BYAOTqjCAgqAnxccmlwCmTHFEkGhiuBRLVm0kmgrh1vA==,iv:bES6rZrKgSRMkJiF9mMROO5QHfvMVg52nS2T+/xr1g4=,tag:wKbHFirjhWbpF840Jrv6vA==,type:str]
vault_grafana_github_client_id: ENC[AES256_GCM,data:PuuDDtIThbbr+S1X6phgPx3am+o=,iv:NcLxlJ5kJt4cfbkqOr2cKGrUwy7tiWse6V0cpWAhxPM=,tag:owhKvP30R8oPQ+01Sq+qEQ==,type:str]
vault_grafana_github_client_secret: ENC[AES256_GCM,data:T3UP/MfL3rSU/qNytA1jTTgKvI0HFTHP/TfB84EsN9SMCBsX9UQOug==,iv:+9OO/qjvYioD9KQzmxW3afO3TMT6LGIZWHQY4GCwFoY=,tag:IQXv6KrXLYevLvfh2OREiA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEV1dOSTh2V0ttV2duZ3Ey
            TEZsWEZRdHhGWWVEUFlGNDA0aW5uLzZSUVdjCmpPMTVvVlV4aU9LYzVvazJnRGRu
            VVdySFdzdXErdUdYQVlDTjR5YTlLUVEKLS0tIGNPK3pjQ3lUNzhjZldRN1hpMllp
            ZDRWNXF2Zkpic1F3emp4OXRJMWdEeW8K65Gg37MyoXiu/qLpEbH/V80KhpXmUL3C
            AVSOuOVBELUwI8FPI+rsRvtrx9yqi3VLdpwcA3mzfgXl306ht25K9A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zf52l3jaxrry857g9xwg3epj0nk4n6q0rsey57psne2lrck3430qazcjdz
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOY0o5UEJyL2lhZXdsMi9a
            YXRqNFBSMk1ENmxxT1FJOW8veEdOajhsOFNzCkF4M1l1VS9IZ2lzeUozNlFxbUNK
            Qk5nZkh0TFdQT0l2QUFsK0hkMzltS28KLS0tIG1hUVQ0VWFGampLY0I3Wk9VMUtk
            T09jdzI4S3R5WVRKZERoUTYvRUVJYnMKUH8D5EgzOl43plH127IGpo2nimKlznuO
            MaxvfwZxqFiRJWfNRnYsghhLC0+tQVvwCbbb+F+BkFJ+bdShPHkIMA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1rzuatatdu7kakf8vugnvjkgzay64uaegwdkgwm02zk50pf0hdv7qqsk677
    lastmodified: "2026-10-10T08:21:51Z"
    mac: ENC[AES256_GCM,data:i7Wf4/uR8sEyuNSqjT1lxO/5ad1xypGM5L/0lBi2IKfBaVsM40p8H56+WeSnF6ukSCQkdE1Pufpf2zNJ2iQccf6CeRkrNB9bmlAKfTwBKHHk2M+iI2a5mhtHjo9kr2TceM50Xq7RpsEZtAcwTZda+ARXwahsxSHtcZec0gbcHiQ=,iv:uRg3lRZ63/cg7lotgd92VCbb7iSz+DKR9JV6E6wBhnM=,tag:uq5DsPGYWN+uXI/J9vo81g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
