---
- name: restart systemd-timesyncd
  ansible.builtin.systemd:
    name: systemd-timesyncd
    state: restarted

- name: reconfigure keyboard
  ansible.builtin.command: dpkg-reconfigure -f noninteractive keyboard-configuration
  notify: restart console-setup

- name: restart console-setup
  ansible.builtin.systemd:
    name: console-setup
    state: restarted
