---
- name: restart systemd-timesyncd
  systemd:
    name: systemd-timesyncd
    state: restarted

- name: reconfigure keyboard
  command: dpkg-reconfigure -f noninteractive keyboard-configuration
  notify: restart console-setup

- name: restart console-setup
  systemd:
    name: console-setup
    state: restarted
