name: Terraform Lint and Plan
on:
    pull_request:
        branches:
            - production
    workflow_dispatch:
      inputs:
        target_env:
          description: "Target environment"
          required: false
          default: "all"

jobs:
    Lint:
        name: Lint
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: terraform
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Cache Plugin Directory
              uses: actions/cache@v4
              with:
                path: ~/.tflint.d/plugins
                key: ${{ runner.os }}-tflint-${{ hashFiles('terraform/.tflint.hcl') }}

            - name: Set up TFlint
              uses: terraform-linters/setup-tflint@v4
              with:
                tflint_version: v0.57.0
            - name: Show version
              run: tflint --version
            
            - name: Init TFlint
              run: tflint --init
              env:
                GITHUB_TOKEN: ${{ github.token }}

            - name: Run TFlint
              run: tflint --recursive -f compact
              
    
    Select_environment:
        name: Select environment
        runs-on: ubuntu-latest
        if : ${{ github.event_name == 'workflow_dispatch' }}
        outputs:
            target_env: ${{ steps.set_env.outputs.target_env }}
        defaults:
            run:
                working-directory: ./terraform/environments
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
          
          - name: List environments
            id: list_env
            run: echo "environments=$(ls -d */ | jq -Rsc 'split("\n")[0:-1] | map(gsub("/"; ""))')" >> $GITHUB_OUTPUT

          - name: Select environment
            id: set_env
            # find the directory name that matches the input
            run: |
              ENVIRONMENTS=${{ steps.list_env.outputs.environments }}
              echo "Available environments: $ENVIRONMENTS"
              echo "Input target_env: ${{ inputs.target_env }}"
              
              target_env=()

              if [[ "${{ inputs.target_env }}" == "all" ]]; then
                target_env=($ENVIRONMENTS)
              else
                while read -r $ENVIRONMENTS; do
                  if [[ "$ENVIRONMENTS" == *"${{ inputs.target_env }}"* ]]; then
                    target_env+=("$ENVIRONMENTS")
                    break
                  fi
                done <<< "$ENVIRONMENTS"
              fi

              # convert target_env array to JSON
              target_env_json=$(printf '%s\n' "${target_env[@]}" | jq -R . | jq -s .)
              echo "target_env_json: $target_env_json"


    Extract_environment:
        name: Extract environment
        runs-on: ubuntu-latest
        if: ${{ github.event_name == 'pull_request' }}
        steps:
          - name: Checkout code
            uses: actions/checkout@v4
          
    Plan:
        name: Plan
        runs-on: ubuntu-latest
        needs: [Select_environment, Extract_environment]
        if: ${{ always()}}
        steps:
          - name: Tailscale
            uses: tailscale/github-action@v3
            with:
              oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
              oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
              tags: tag:ci
              use-cache: true
          - name: Check connection
            run: ping -c 1 ${{ secrets.TARGET_HOST }}
